-- CREATE DATABASE IF NOT EXISTS enq12nov25;
-- USE enq12nov25;

CREATE TABLE IF NOT EXISTS student (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    tel VARCHAR(20) NOT NULL,
    lang VARCHAR(255),
    location VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    dept VARCHAR(100) NOT NULL,
    course VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
